apiVersion: apps/v1
kind: Deployment
metadata:
  name: useless-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: useless-operator
  template:
    metadata:
      labels:
        name: useless-operator
    spec:
      serviceAccountName: useless-operator
      containers:
        - name: useless-operator
          image: quay.io/cwilkers/useless-operator:v0.0.1
          command:
          - useless-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "useless-operator"
